export const courseContent = [
  { id: 1, type: "module", name: "الوحدة الاولى", firstOrder: 0 },
  { id: 1, type: "lesson", name: "الاهداف", order: 0 },
  { id: 2, type: "lesson", name: "الدرس الاول", order: 1 },
  { id: 19, type: "exam", name: "اختبر نفسك", order: 2 },
  { id: 3, type: "lesson", name: "الدرس الثانى", order: 3 },
  { id: 5, type: "activity", name: "نشاط", order: 4 },
  { id: 4, type: "lesson", name: "الدرس الثالث", order: 5 },
  { id: 17, type: "exam", name: "امتحان الوحدة الاول", order: 6, module_id: 1 },
  { id: 2, type: "module", name: "الوحدة الثانية", firstOrder: 7 },
  { id: 11, type: "lesson", name: "الاهداف", order: 7 },
  { id: 12, type: "lesson", name: "الدرس الاول", order: 8 },
  { id: 15, type: "activity", name: "نشاط", order: 9 },
  { id: 13, type: "lesson", name: "الدرس الثانى", order: 10 },
  { id: 20, type: "exam", name: "اختبر نفسك", order: 11 },
  { id: 14, type: "lesson", name: "الدرس الثالث", order: 12 },
  {
    id: 22,
    type: "exam",
    name: "امتحان الوحدة الثانى",
    order: 13,
    module_id: 3,
  },
  { id: 3, type: "module", name: "الوحدة الثالثة", firstOrder: 14 },
  { id: 17, type: "lesson", name: "الاهداف", order: 14 },
  { id: 18, type: "lesson", name: "الدرس الاول", order: 15 },
  { id: 19, type: "activity", name: "نشاط 1", order: 16 },
  { id: 20, type: "lesson", name: "الدرس الثانى", order: 17 },
  { id: 23, type: "exam", name: "اختبر نفسك", order: 18 },
  {
    id: 24,
    type: "exam",
    name: "امتحان الوحدة الثالث",
    order: 19,
    module_id: 4,
  },
  { id: 4, type: "module", name: "الوحدة الرابعة", firstOrder: 20 },
  { id: 21, type: "lesson", name: "الاهداف", order: 20 },
  { id: 22, type: "lesson", name: "الدرس الاول", order: 21 },
  { id: 23, type: "activity", name: "نشاط 1", order: 22 },
  { id: 24, type: "lesson", name: "الدرس الثانى", order: 23 },
  { id: 25, type: "activity", name: "نشاط 2", order: 24 },
  {
    id: 25,
    type: "exam",
    name: "امتحان الوحدة الرابعة",
    order: 25,
    module_id: 5,
  },
];
