export const courseContent = [
  { id: 1, type: "module", name: "الوحدة الأولى", firstOrder: 0 },
  { id: 1, type: "lesson", name: "الأهداف", order: 0 },
  { id: 2, type: "lesson", name: "الدرس الأول", order: 1 },
  { id: 19, type: "exam", name: "اختبر نفسك", order: 2 },
  { id: 3, type: "lesson", name: "الدرس الثانى", order: 3 },
  { id: 5, type: "activity", name: "نشاط", order: 4 },
  { id: 4, type: "lesson", name: "الدرس الثالث", order: 5 },
  { id: 17, type: "exam", name: "اختبار الوحدة الأول", order: 6, module_id: 1 },
  { id: 3, type: "module", name: "الوحدة الثانية", firstOrder: 7 },
  { id: 11, type: "lesson", name: "الأهداف", order: 7 },
  { id: 12, type: "lesson", name: "الدرس الأول", order: 8 },
  { id: 15, type: "activity", name: "نشاط", order: 9 },
  { id: 13, type: "lesson", name: "الدرس الثانى", order: 10 },
  { id: 20, type: "exam", name: "اختبر نفسك", order: 11 },
  { id: 14, type: "lesson", name: "الدرس الثالث", order: 12 },
  {
    id: 22,
    type: "exam",
    name: "اختبار الوحدة الثانى",
    order: 13,
    module_id: 3,
  },
  { id: 4, type: "module", name: "الوحدة الثالثة", firstOrder: 14 },
  { id: 17, type: "lesson", name: "الأهداف", order: 14 },
  { id: 18, type: "lesson", name: "الدرس الأول", order: 15 },
  { id: 19, type: "activity", name: "نشاط", order: 16 },
  { id: 20, type: "lesson", name: "الدرس الثانى", order: 17 },
  { id: 23, type: "exam", name: "اختبر نفسك", order: 18 },
  {
    id: 24,
    type: "exam",
    name: "اختبار الوحدة الثالث",
    order: 19,
    module_id: 4,
  },
  { id: 5, type: "module", name: "الوحدة الرابعة", firstOrder: 20 },
  { id: 21, type: "lesson", name: "الأهداف", order: 20 },
  { id: 22, type: "lesson", name: "الدرس الأول", order: 21 },
  { id: 23, type: "activity", name: "نشاط", order: 22 },
  { id: 24, type: "lesson", name: "الدرس الثانى", order: 23 },
  { id: 25, type: "activity", name: "نشاط", order: 24 },
  {
    id: 25,
    type: "exam",
    name: "اختبار الوحدة الرابعة",
    order: 25,
    module_id: 5,
  },
];

export const courseContentWithModules = [
  {
    id: 1,
    name: "الوحدة الأولى",
    items: [
      { id: 1, type: "lesson", name: "الأهداف", order: 0 },
      { id: 2, type: "lesson", name: "الدرس الأول", order: 1 },
      { id: 19, type: "exam", name: "اختبر نفسك", order: 2 },
      { id: 3, type: "lesson", name: "الدرس الثانى", order: 3 },
      { id: 5, type: "activity", name: "نشاط", order: 4 },
      { id: 4, type: "lesson", name: "الدرس الثالث", order: 5 },
      {
        id: 17,
        type: "exam",
        name: "اختبار الوحدة الأول",
        order: 6,
        module_id: 1,
      },
    ],
  },
  {
    id: 3,
    name: "الوحدة الثانية",
    items: [
      { id: 11, type: "lesson", name: "الأهداف", order: 7 },
      { id: 12, type: "lesson", name: "الدرس الأول", order: 8 },
      { id: 15, type: "activity", name: "نشاط", order: 9 },
      { id: 13, type: "lesson", name: "الدرس الثانى", order: 10 },
      { id: 20, type: "exam", name: "اختبر نفسك", order: 11 },
      { id: 14, type: "lesson", name: "الدرس الثالث", order: 12 },
      {
        id: 22,
        type: "exam",
        name: "اختبار الوحدة الثانى",
        order: 13,
        module_id: 3,
      },
    ],
  },
  {
    id: 4,
    name: "الوحدة الثالثة",
    items: [
      { id: 17, type: "lesson", name: "الأهداف", order: 14 },
      { id: 18, type: "lesson", name: "الدرس الأول", order: 15 },
      { id: 19, type: "activity", name: "نشاط", order: 16 },
      { id: 20, type: "lesson", name: "الدرس الثاني", order: 17 },
      { id: 23, type: "exam", name: "اختبر نفسك", order: 18 },
      {
        id: 24,
        type: "exam",
        name: "اختبار الوحدة الثالث",
        order: 19,
        module_id: 4,
      },
    ],
  },
  {
    id: 5,
    name: "الوحدة الرابعة",
    items: [
      { id: 21, type: "lesson", name: "الأهداف", order: 20 },
      { id: 22, type: "lesson", name: "الدرس الأول", order: 21 },
      { id: 23, type: "activity", name: "نشاط", order: 22 },
      { id: 24, type: "lesson", name: "الدرس الثانى", order: 23 },
      { id: 25, type: "activity", name: "نشاط", order: 24 },
      {
        id: 25,
        type: "exam",
        name: "اختبار الوحدة الرابعة",
        order: 25,
        module_id: 5,
      },
    ],
  },
];
